app = "dda-reu-wang"  # 앱 이름 (Fly.io에서 생성된 이름)
primary_region = "nrt"  # 일본 리전 (Fly.io에서 선택한 리전)

[build]
  dockerfile = "flask_server/Dockerfile"  # Dockerfile 위치 지정

[env]
  PORT = "8080"  # Flask가 실행될 포트 지정

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
